### ISSUE TITLE
Missing txt files

### ISSUE THREAD

**Issue by algiraldohe** [Zhenye-Na/image-similarity-using-deep-ranking#13]
Hello I'm receiving the following error while trying to execute this command:
python3 acc_knn.py --predict_similar_images "../tiny-imagenet-200/test/images/test_9970.JPEG" --predict_top_N 5

==> Preparing Tiny ImageNet dataset ...
Get all training images, Done ... | Time elapsed 74.98976492881775s
Traceback (most recent call last):
  File "acc_knn.py", line 238, in <module>
    main()
  File "acc_knn.py", line 229, in main
    embedding_space = load_train_embedding()
  File "acc_knn.py", line 33, in load_train_embedding
    embedding_space = np.fromfile("../embedded_features_train.txt", dtype=np.float32)
FileNotFoundError: [Errno 2] No such file or directory: '../embedded_features_train.txt'

I looked for the file but is not on the repo. Can someone help me to sort this out? Or does the file can be gotten from somewhere?

Thanks

**Comment by imneonizer** [comment]
Hey @algiraldohe you can try this repository https://github.com/imneonizer/pytorch-triplet-loss

**Comment by Zhenye-Na** [comment]
> Hello I'm receiving the following error while trying to execute this command: python3 acc_knn.py --predict_similar_images "../tiny-imagenet-200/test/images/test_9970.JPEG" --predict_top_N 5
> 
> ==> Preparing Tiny ImageNet dataset ... Get all training images, Done ... | Time elapsed 74.98976492881775s Traceback (most recent call last): File "acc_knn.py", line 238, in main() File "acc_knn.py", line 229, in main embedding_space = load_train_embedding() File "acc_knn.py", line 33, in load_train_embedding embedding_space = np.fromfile("../embedded_features_train.txt", dtype=np.float32) FileNotFoundError: [Errno 2] No such file or directory: '../embedded_features_train.txt'
> 
> I looked for the file but is not on the repo. Can someone help me to sort this out? Or does the file can be gotten from somewhere?
> 
> Thanks

Perhaps you need to run [this](https://github.com/Zhenye-Na/image-similarity-using-deep-ranking/blob/master/src/sampler.py) file first.

**Comment by tieckit** [comment]
use this.
```python 
python src/accuracy.py 
```
