### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by hodaatef** [Zhenye-Na/image-similarity-using-deep-ranking#3]
```
==> Preparing Tiny ImageNet dataset ...
==> Retrieve model parameters ...
Get all test image classes, Done ... | Time elapsed 0.015627145767211914s
Get all training images, Done ... | Time elapsed 1.7184438705444336s
Get embedded_features, Done ... | Time elapsed 2935.702290058136s
Now processing 0th test image
Traceback (most recent call last):
  File "D:\deep-ranking\model7\accuracy.py", line 206, in <module>
    main()
  File "D:\deep-ranking\model7\accuracy.py", line 202, in main
    calculate_accuracy(trainloader, testloader, args.is_gpu)
  File "D:\deep-ranking\model7\accuracy.py", line 112, in calculate_accuracy
    embedded_test_numpy, (embedded_features_train.shape[0], 1))
  File "C:\Users\DoDo\Anaconda3\envs\deep-ranking\lib\site-packages\numpy\lib\shape_base.py", line 1241, in tile
    c = c.reshape(-1, n).repeat(nrep, 0)
MemoryError
>>> 
```

whats is the problem ..
can any one help me please ??

**Comment by Zhenye-Na** [comment]
what is your batch size?
